name: finances
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #animacoes
  lottie: ^1.1.0
  #sqlite
  sqflite: ^2.0.2
  #para manipular caminhos
  path: any
  path_provider: ^2.0.11
  #mobx
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  #icones
  flutter_launcher_icons: ^0.9.2
  #efeitos de deslizar no item
  flutter_slidable: ^0.6.0
  #para salvar valores como token ou nome na memoria interna
  shared_preferences: ^2.0.15
  #formatar data
  intl: ^0.17.0
  showcaseview: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/images/logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/lottie/
    - lib/core/assets/images/
    - lib/core/assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/core/assets/fonts/poppins_regular.ttf
